---
title: "Datasaurus"
author: "oggismetto"
date: "13/10/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}

Sys.setlocale("LC_TIME", "en_US.UTF-8")

library(tidyverse)
library(here)
library(tidytuesdayR)
library(scales)
library(maps)
library(ggtext)

theme_set(theme_light())

# Read in with tidytuesdayR package 
# Install from CRAN via: install.packages("tidytuesdayR")
# This loads the readme and all the datasets for the week of interest

# Either ISO-8601 date or year/week works!

tuesdata <- tidytuesdayR::tt_load(2020, week = 36)

key_crop_yields <- tuesdata$key_crop_yields

# Or read in the data manually
key_crop_yields <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/key_crop_yields.csv')
fertilizer <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/cereal_crop_yield_vs_fertilizer_application.csv')
tractors <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/cereal_yields_vs_tractor_inputs_in_agriculture.csv')
land_use <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/land_use_vs_yield_change_in_cereal_production.csv')
arable_land <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/arable_land_pin.csv')

```


```{r}

wheat_yield <- 
  key_crop_yields %>%
  select(Entity, Year, `Wheat (tonnes per hectare)`)

```

map of changing in wheat production over time

```{r}

world <- map_data("world") %>%
  filter(region != "Antarctica")

wheat_yield %>%
  group_by(Entity)%>%
  summarize(mean = mean(`Wheat (tonnes per hectare)`)) %>%
  arrange(desc(mean))

wheat_yield %>%
  filter(Year %in% c("1970", "1980", "1990","2000", "2010", "2018")) %>%
  rename(Yield = (`Wheat (tonnes per hectare)`)) %>%
  full_join(world, by = c(Entity = "region")) %>% 
  filter(Year != "2020", !is.na(Yield)) %>%
  ggplot(aes(long, lat, group = group, fill = Yield)) +
  geom_polygon() +
  theme_void() +
  scale_fill_gradient2(low = "yellow", 
                       high = "red", 
                       mid = "orange", 
                       midpoint = 5) +
  labs(title = "Wheat yield over time",
       subtitle = "Yield expressed as tonnes per hectare",
       caption = "by @GoldenB16117397 | source: #TidyTuesday/Global Crop Yield") +
  facet_wrap(~Year)+
  theme(
    legend.position = "bottom",
    plot.background = element_rect(fill = "grey20"),
    text = element_text(color = "white"),
    plot.title = element_markdown(hjust = .5, size = 26, 
                            margin = margin(b = 8), face = "bold" ,family = "Mono"),
    plot.subtitle = element_markdown(size = 14, hjust = .5, 
                            margin = margin(b = 16), family = "Mono"),
    plot.caption = element_markdown(size = 8, family = "Mono"),
    legend.title = element_text(size = 5, family = "Mono"),
    legend.text = element_text(size = 4, family = "Mono"),
    strip.text = element_markdown(size = 6, family = "Mono")
  ) 

ggsave(here("plots","2020_36","Wheat_Yield.png"),
       width = 12, height = 6, units = 'in', dpi = 300)

```

