---
title: "gdpr"
author: "oggismetto"
date: "21/04/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(patchwork)
library(hrbrthemes)
library(scales)

gdpr_violations <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-21/gdpr_violations.tsv')
```

# What are the most common violations?
```{r}

p1 <- gdpr_violations %>%
    mutate(type = fct_lump(type, 4)) %>%
    group_by(price = cut(price, c(0, 1000, 10000, 50000, 100000, Inf),
                                    labels = c("<1K", "1K-10K", "10K-50K", "50K-100K", "100K+"))) %>%
    count(type, sort = T) %>%
    filter(price != "NA") %>%
    ggplot(aes(x = price, y = n, fill = fct_relevel(type, "Non-compliance with lawful basis for data processing", "Failure to implement sufficient measures to ensure information security"))) +
    geom_col() +
    theme_ft_rc() +
    labs(title = "How much should i pay and for what?",
         x = "price of the fine",
         y = "number of violations",
         fill = "Type of violation") +
    expand_limits(y = 80) +
  coord_flip()

```

```{r}

gdpr_violations_country <- gdpr_violations %>%
  group_by(name) %>%
  summarize(price = sum(price),
            n = n()) %>%
  arrange(desc(price)) %>%
  head(10)

gdpr_violations_controllers <- gdpr_violations %>%
    group_by(name) %>%
    select(name, price, controller) %>%
    filter(price == max(price))

gdpr_violations_controllers_country <- 
  gdpr_violations_controllers %>%
    inner_join(gdpr_violations_country, by = "name") %>%
    select(name, controller, price.y, n) %>%
    rename(price = price.y) %>%
  unique()

p2 <- gdpr_violations_controllers_country %>%
  ggplot(aes(x = reorder(name,price), y = price)) +
  geom_point(aes(size = n), color = "white") +
  theme_ft_rc() +
  labs(title = "Fines by country (top 10 countries)",
       x = "",
       y = "Total amount in fines (log10)",
       size = "Number of fines")+
  scale_y_log10(labels = dollar_format(suffix = "€", prefix = "")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  expand_limits(y = 100000000) +
  geom_text_repel(aes(label = controller), 
                  size = 3, 
                  color = "grey", 
                  fontface = 'bold', 
                  nudge_x = ifelse(gdpr_violations_controllers_country$name %in% c("Spain", "Italy"), -1.5, 0), 
                  nudge_y = ifelse(gdpr_violations_controllers_country$name %in% c("Spain", "Italy"), 0.2, 0))




```

```{r}
# save p1 and p2
png("/scratch/git/tidytuesday/plots/2020_17/17_2020_GDPR_1.png", 
    width = 10, height = 5, units = 'in', res = 300)
p1
dev.off()

# save p1 and p2
png("/scratch/git/tidytuesday/plots/2020_17/17_2020_GDPR_2.png", 
    width = 10, height = 5, units = 'in', res = 300)
p2
dev.off()

```

---

# Additional analyses
# What's the amount of fine?
```{r}

gdpr_violations %>%
    ggplot(aes(x = price)) +
    geom_histogram() +
    scale_x_log10(labels = dollar_format(suffix = "€", prefix = "")) +
    labs(title = "How much is it Sir?",
         x = "Price",
         y = "Count") +
    theme_ft_rc() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

# What are the most common types of violation?
```{r}
gdpr_violations %>%
    count(type, sort = T) %>%
    filter(n>5) %>%
    ggplot(aes(x = reorder(type,n), y = n))+
    geom_col() +
    coord_flip() +
    theme_ft_rc() +
  labs(title = "The most common types of violation?",
       x = "", y= "")
```

