---
title: "African American Achievements"
author: "oggismetto"
date: "08/06/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}

Sys.setlocale("LC_TIME", "en_US.UTF-8")

library(tidyverse)
library(here)
library(cowplot)
library(ggridges)
library(tidytext)
require(devtools)
# install_github("lchiffon/wordcloud2")
library(wordcloud2)

# Get the Data

firsts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-09/firsts.csv')
science <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-09/science.csv')


```


```{r}
# density count

density <- firsts %>%
  select(year, category) %>%
  mutate(decade = year %/% 10 * 10) %>%
  count(decade, category) %>% 
  ggplot(aes(x = decade, y = fct_rev(category), height = n)) +
  geom_ridgeline(scale = 0.1, alpha = 0.6, fill = "black", colour = "white") + 
  theme_ridges(grid = FALSE, font_size = 12) +
  labs(x = "decade",
       y = "category")

```

# wordplot with shape of a MLK

```{r}

accomplishments <- firsts %>%
  select(accomplishment) %>%
  unnest_tokens(word, accomplishment) %>%
  filter(!word %in% c("first", "american","african")) %>%
  anti_join(stop_words) %>%
  count(word)

wordcloud2(accomplishments, figPath = "other/img/mlk.jpeg", size  =1.5, color = 'black')

# wordcloud2 has a bug and you need to refresh the page in the browser to get the plot
# then you have to save it in png format
```

# Combine the figures and save the plot

```{r}
african_american <- ggdraw() +
  draw_image(here("other", "imgs", "mlk_wordcloud.png"), hjust = 0, x = 0.1, y = -0.05, scale = 0.8)+
  draw_plot(density, scale = 0.43, x = -0.29, y = 0.13) + 
  draw_label("African American Achievements, a complex history", color = "black", size = 25, angle = 0, y = 0.95) +
  draw_label("When we allow freedom to ring-when we let it ring
\nfrom every city and every hamlet, from every state and
\nevery city, we will be able to speed up that day when all
\nof God's children, black men and white men, Jews and
\nGentiles, Protestants and Catholics, will be able to join
\nhands and sing in the words of the old Negro spiritual,
\n\"Free at last, Free at last, Great God a-mighty, We are
\nfree at last\"
\n(MARTIN LUTHER KING JR., 1963) ", color = "black", size = 7, angle = 0, x = 0.2, y = 0.23, fontfamily = "TT Courier New") + 
  draw_label("by @GoldenB16117397 | source: TidyTuesday | African American Achievements", color = "black", size = 6, angle = 0, x = 0.8, y = 0.05)+ 
  draw_label("#BlackLivesMatter", color = "black", size = 10, angle = 0, x = 0.88, y = 0.8, fontface = "bold")+ 
  draw_label("Breakdown of african american achievements over time and summarized in one of their most popular heroes", color = "black", size = 12, angle = 0, x = 0.5, y = 0.88)

african_american
ggsave(here("plots","2020_24", "african_american.png"), 
    width = 9, height = 5, units = 'in', dpi = 300)
```


