---
title: "Spice Girls"
author: "oggismetto"
date: "14/12/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}

Sys.setlocale("LC_TIME", "en_US.UTF-8")

library(tidyverse)
library(here)
library(tidytuesdayR)
library(tidytext)
library(ggtext)
library(lubridate)

theme_set(theme_light())
dir.create("/scratch/git/tidytuesday/plots/2021_51/")

#1  Get the Data
tuesdata <- tidytuesdayR::tt_load('2021-12-14')
studio_album_tracks <- tuesdata$studio_album_tracks

```

```{r}

studio_album_tracks_normalized <- 
  studio_album_tracks %>%
  select(track_name, danceability:tempo, -c(key, mode)) %>%
  column_to_rownames("track_name") %>%
  scale(.) %>%
  as_data_frame()


correlations <- tibble(danceability  = cor(studio_album_tracks_normalized$valence, studio_album_tracks_normalized$danceability),
                       energy  = cor(studio_album_tracks_normalized$valence, studio_album_tracks_normalized$energy),
                       loudness  = cor(studio_album_tracks_normalized$valence, studio_album_tracks_normalized$loudness),
                       speechiness = cor(studio_album_tracks_normalized$valence, studio_album_tracks_normalized$speechiness),
                       instrumentalness  = cor(studio_album_tracks_normalized$valence, studio_album_tracks_normalized$instrumentalness),
                       liveness  = cor(studio_album_tracks_normalized$valence, studio_album_tracks_normalized$liveness),
                       tempo  = cor(studio_album_tracks_normalized$valence, studio_album_tracks_normalized$tempo)) %>%
  pivot_longer(everything()) %>% rename(cor = value) %>% mutate(cor = round(cor, 2))

studio_album_tracks_normalized %>%
  pivot_longer(c(danceability:liveness, tempo)) %>%
  inner_join(correlations, by = "name") %>%
  mutate(name = factor(name, levels = c("danceability", "energy", "instrumentalness", "speechiness", "loudness", "tempo", "liveness"))) %>%
  ggplot(aes(x = valence, y = value, color = name)) +
  geom_point() +
  geom_text(aes(x = 0, y = 3, label = cor, hjust = 0, vjust = 0, family = "Purisa"),size = 5) +
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~name, nrow = 1) +
  labs(title = "Valence correlated with all Spotify metrics for Spice Girls tracks",
       subtitle = "Valence is a measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track",
       x = "", y = "") +
  theme(legend.position = "none",
        title = element_text(family = "Purisa", face = "bold", size = 18),
        strip.background = element_rect(fill = "#1DB954"),
        strip.text = element_text(color = "#191414", face = "bold", size = 15, family = "Purisa"),
        plot.background = element_rect(fill = "#1DB954"),
        panel.background = element_rect(fill = "#191414"),
        panel.grid = element_line(size = 0.1))

ggsave(filename = "/scratch/git/tidytuesday/plots/2021_51/test.png", width = 30, height = 7, dpi = 300, units = "cm")

```

another similar tidytuesday

```{r}

library(tidyverse)
library(corrplot)
library(corrr)
library(RColorBrewer)
library(showtext)

# Helper function for caption
`%+%` <- function(x, y) paste0(x, y)

# Get fonts
font_add_google("Rock Salt", "rs")
showtext_auto()

# Load data
data <- tidytuesdayR::tt_load("2021-12-14")

# Select numeric variables
c <- data$studio_album_tracks %>%
  select(danceability,
         energy,
         speechiness,
         acousticness,
         instrumentalness,
         liveness,
         valence,
         tempo)

# Calculate correlation, put in df
df_c <- c %>%
  correlate()

# Transform for plotting, then plot
df_c %>%
  pivot_longer(-term, names_to = "group", values_to = "corr") %>%
  filter(term == "danceability" & !is.na(corr)) %>%
  mutate(group = str_to_title(group),
         budge = case_when(corr > 0 ~ -.075,
                           corr < 0 ~ .075, 
                           TRUE ~ 0),
         align = case_when(corr > 0 ~ 1,
                           corr < 0 ~ 0,
                           TRUE ~ 0)) %>%
  ggplot(aes(reorder(group, corr), corr)) +
  geom_hline(yintercept = 0, linetype = 3) +
  geom_segment(aes(x = reorder(group, corr), xend = reorder(group, corr),
                   y = 0, yend = corr),
               linetype = 4, size = 1.5, color = "grey30") +
  geom_point(size = 12, aes(fill = corr), shape = 21) +
  geom_text(aes(label = round(corr, digits = 2),
                color = ifelse(abs(corr) < .2, "black", "white")),
            size = 2, family = "rs") +
  geom_text(aes(label = group, 
                y = budge, hjust = align), family = "rs", color = "#340E51") +
  scale_fill_gradient2(low = "#D12424", mid = "white", high = "#f28bd5") +
  scale_color_manual(values = c("black", "white")) +
  scale_y_continuous(breaks = c(-.45, .55), labels = c("Less Danceable", "More Danceable")) +
  theme_minimal() + 
  theme(legend.position = "none",
        text = element_text(family = "rs", color = "#340E51"),
        plot.caption = element_text(hjust = 0, size = 8, lineheight = 1.25),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.y = element_blank(),
        plot.title.position = "plot",
        plot.caption.position = "plot",
        axis.line.x = element_line(arrow = arrow(length = unit(.3, "cm"), ends = "both"),
                                   color = "grey30")) +
  labs(x = "", y = "",
       title = "What makes a Spice Girls song danceable?",
       subtitle = "Sugar, spice, and a whole lot of valence",
       caption =  "Valence is a measure of musical positiveness.\n" %+%
         "Numbers represent correlation with Spotify's danceability metric.\n" %+%
         "Graph by Spencer Schien (@MrPecners) | Data from Spotify") +
  coord_flip()

ggsave(filename = "2021/2021-12-14/final_plot.jpeg", device = "jpeg")

```

