---
title: "Tour_de_France_070420"
author: "oggismetto"
date: "4/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, Prep the data, , include=FALSE, echo = FALSE}
library(tidytuesdayR)
library(tidyverse)

#library(tidytext)
#library(wordcloud)
```


```{r, Prep the data}
tuesdata <- tidytuesdayR::tt_load(2020, week = 15)

tdf_winners <-  
  tuesdata$tdf_winners


png("/scratch/git/tidytuesday/week15/week15.png",
    width = 7, height = 5, units = 'in', res = 300)

tdf_winners %>%
    group_by(winner_team) %>%
    summarize(age = mean(age),
              n = n()) %>%
    filter(n > 5) %>%
    ggplot(aes(x=reorder(winner_team,n), y = n, fill = winner_team)) +
    geom_col(show.legend = FALSE) +
    geom_line(aes(y = age/2, group = 1)) +
    scale_y_continuous(sec.axis = sec_axis(~. *2, name = "Average age")) +
    coord_flip() +
    labs(title = "What about the youngest and oldest most winning teams?", x = "",y = "number of won TDF") +
    theme_bw()

dev.off()
```

